version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydb
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    web:
        build: .
        ports:
            - '3000:3000'
        environment:
            DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
        volumes:
            - .:/app
        command: ['./wait-for-it.sh', 'postgres:5432', '--', 'sh', '-c', 'npx prisma migrate dev && npm run dev']

volumes:
    postgres-data:
